import type { ComponentType, ComponentCategory, ComponentConfig } from '../../types';

export interface ComponentDefinition {
  type: ComponentType;
  category: ComponentCategory;
  label: string;
  description: string;
  icon: string;
  color: string;
  defaultConfig: ComponentConfig;
  // Baseline resource usage at 100% load
  baseCpuPct: number;
  baseRamPct: number;
  baseLatencyMs: number;
  // Can accumulate storage?
  accumulatesStorage: boolean;
  // Is a source node (generates requests)?
  isSource: boolean;
  // Is a sink node (consumes requests without forwarding)?
  isSink: boolean;
}

export const COMPONENT_DEFINITIONS: Record<ComponentType, ComponentDefinition> = {
  // === CLIENTS ===
  'client': {
    type: 'client',
    category: 'client',
    label: 'Client',
    description: 'Browser-based client generating HTTP/REST requests',
    icon: '🌐',
    color: '#6366f1',
    defaultConfig: { replicas: 1, maxRps: 1000, label: 'Web Client', timeoutMs: 5000 },
    baseCpuPct: 10,
    baseRamPct: 20,
    baseLatencyMs: 0,
    accumulatesStorage: false,
    isSource: true,
    isSink: false,
  },
  'mobile': {
    type: 'mobile',
    category: 'client',
    label: 'Mobile',
    description: 'Mobile app generating API requests',
    icon: '📱',
    color: '#8b5cf6',
    defaultConfig: { replicas: 1, maxRps: 500, label: 'Mobile Client', timeoutMs: 5000 },
    baseCpuPct: 5,
    baseRamPct: 10,
    baseLatencyMs: 0,
    accumulatesStorage: false,
    isSource: true,
    isSink: false,
  },

  // === TRAFFIC & EDGE ===
  'dns': {
    type: 'dns',
    category: 'traffic-edge',
    label: 'DNS',
    description: 'Domain Name System routing traffic to the nearest edge',
    icon: '🌍',
    color: '#3b82f6',
    defaultConfig: { replicas: 1, maxRps: 100000, label: 'DNS Server', timeoutMs: 1000, connectionPool: 5000 },
    baseCpuPct: 5,
    baseRamPct: 10,
    baseLatencyMs: 2,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'cdn': {
    type: 'cdn',
    category: 'traffic-edge',
    label: 'CDN',
    description: 'Content Delivery Network — caches static assets globally',
    icon: '🌍',
    color: '#06b6d4',
    defaultConfig: { replicas: 1, maxRps: 100000, cacheHitRate: 0.85, label: 'CDN Cache', timeoutMs: 1000, connectionPool: 5000 },
    baseCpuPct: 10,
    baseRamPct: 30,
    baseLatencyMs: 5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'load-balancer': {
    type: 'load-balancer',
    category: 'traffic-edge',
    label: 'Load Balancer',
    description: 'Distributes traffic across multiple servers (e.g. Nginx, ALB)',
    icon: '⚖️',
    color: '#0ea5e9',
    defaultConfig: { replicas: 2, maxRps: 50000, label: 'Load Balancer', timeoutMs: 1500, connectionPool: 2000 },
    baseCpuPct: 15,
    baseRamPct: 20,
    baseLatencyMs: 1,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'waf': {
    type: 'waf',
    category: 'traffic-edge',
    label: 'WAF',
    description: 'Web Application Firewall filtering malicious requests',
    icon: '🛡️',
    color: '#ef4444',
    defaultConfig: { replicas: 2, maxRps: 40000, label: 'Edge WAF', timeoutMs: 1500, connectionPool: 2000 },
    baseCpuPct: 20,
    baseRamPct: 25,
    baseLatencyMs: 5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'api-gateway': {
    type: 'api-gateway',
    category: 'traffic-edge',
    label: 'API Gateway',
    description: 'Central entry point for routing, authentication and rate limiting',
    icon: '🔀',
    color: '#14b8a6',
    defaultConfig: { replicas: 2, maxRps: 20000, label: 'API Gateway', timeoutMs: 2000, connectionPool: 1000 },
    baseCpuPct: 25,
    baseRamPct: 30,
    baseLatencyMs: 3,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'ingress': {
    type: 'ingress',
    category: 'traffic-edge',
    label: 'Ingress',
    description: 'Kubernetes Ingress controller managing external access to cluster services',
    icon: '🕸️',
    color: '#8b5cf6',
    defaultConfig: { replicas: 2, maxRps: 30000, label: 'Cluster Ingress', timeoutMs: 1500, connectionPool: 1500 },
    baseCpuPct: 15,
    baseRamPct: 20,
    baseLatencyMs: 2,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },

  // === COMPUTE ===
  'app-server': {
    type: 'app-server',
    category: 'compute',
    label: 'App Server',
    description: 'Application server handling core business logic',
    icon: '🖥️',
    color: '#f59e0b',
    defaultConfig: { replicas: 3, maxRps: 2000, cpuCores: 4, ramGb: 16, label: 'App Server', timeoutMs: 5000, connectionPool: 200 },
    baseCpuPct: 60,
    baseRamPct: 50,
    baseLatencyMs: 20,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'worker': {
    type: 'worker',
    category: 'compute',
    label: 'Worker',
    description: 'Background processing node executing async tasks',
    icon: '⚙️',
    color: '#eab308',
    defaultConfig: { replicas: 2, maxRps: 1000, cpuCores: 2, ramGb: 8, label: 'Background Worker', timeoutMs: 10000, connectionPool: 100 },
    baseCpuPct: 45,
    baseRamPct: 40,
    baseLatencyMs: 50,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'serverless': {
    type: 'serverless',
    category: 'compute',
    label: 'Serverless',
    description: 'Ephemeral container-on-demand execution (e.g. AWS Lambda)',
    icon: '⚡',
    color: '#f97316',
    defaultConfig: { replicas: 1, maxRps: 5000, cpuCores: 2, ramGb: 4, label: 'Serverless Function', timeoutMs: 3000 },
    baseCpuPct: 30,
    baseRamPct: 25,
    baseLatencyMs: 30,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'auth-service': {
    type: 'auth-service',
    category: 'compute',
    label: 'Auth Service',
    description: 'Handles user sessions, authentication, and OAuth verification',
    icon: '🔒',
    color: '#ec4899',
    defaultConfig: { replicas: 2, maxRps: 4000, cpuCores: 2, ramGb: 4, label: 'Auth Service', timeoutMs: 1000, connectionPool: 500 },
    baseCpuPct: 40,
    baseRamPct: 30,
    baseLatencyMs: 15,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'search': {
    type: 'search',
    category: 'compute',
    label: 'Search',
    description: 'Text index & search service (Elasticsearch / OpenSearch)',
    icon: '🔍',
    color: '#22c55e',
    defaultConfig: { replicas: 2, maxRps: 3000, cpuCores: 4, ramGb: 16, storageGb: 500, label: 'Search Engine', connectionPool: 500 },
    baseCpuPct: 50,
    baseRamPct: 60,
    baseLatencyMs: 12,
    accumulatesStorage: true,
    isSource: false,
    isSink: false,
  },
  'scheduler': {
    type: 'scheduler',
    category: 'compute',
    label: 'Scheduler',
    description: 'Triggers periodic actions or cron jobs',
    icon: '⏱️',
    color: '#0ea5e9',
    defaultConfig: { replicas: 1, maxRps: 10000, cpuCores: 2, ramGb: 4, label: 'Cron Scheduler', timeoutMs: 2000 },
    baseCpuPct: 10,
    baseRamPct: 15,
    baseLatencyMs: 5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'notifications': {
    type: 'notifications',
    category: 'compute',
    label: 'Notifications',
    description: 'Dispatches push notifications, emails, and SMS alerts',
    icon: '🔔',
    color: '#f43f5e',
    defaultConfig: { replicas: 2, maxRps: 5000, cpuCores: 2, ramGb: 4, label: 'Notification Dispatcher', timeoutMs: 5000, connectionPool: 200 },
    baseCpuPct: 30,
    baseRamPct: 20,
    baseLatencyMs: 8,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'analytics': {
    type: 'analytics',
    category: 'compute',
    label: 'Analytics',
    description: 'Real-time data aggregation and processing stream',
    icon: '📊',
    color: '#8b5cf6',
    defaultConfig: { replicas: 2, maxRps: 2000, cpuCores: 4, ramGb: 16, storageGb: 100, label: 'Stream Analytics', timeoutMs: 5000, connectionPool: 300 },
    baseCpuPct: 50,
    baseRamPct: 55,
    baseLatencyMs: 25,
    accumulatesStorage: true,
    isSource: false,
    isSink: false,
  },

  // === STORAGE ===
  'sql-database': {
    type: 'sql-database',
    category: 'storage',
    label: 'SQL Database',
    description: 'Relational database (PostgreSQL / MySQL)',
    icon: '🐘',
    color: '#3b82f6',
    defaultConfig: { replicas: 1, maxRps: 5000, storageGb: 500, label: 'SQL Database', connectionPool: 100 },
    baseCpuPct: 70,
    baseRamPct: 60,
    baseLatencyMs: 5,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'nosql-db': {
    type: 'nosql-db',
    category: 'storage',
    label: 'NoSQL DB',
    description: 'Document / Key-Value store (MongoDB / DynamoDB / Cassandra)',
    icon: '🍃',
    color: '#22c55e',
    defaultConfig: { replicas: 3, maxRps: 15000, storageGb: 1000, label: 'NoSQL DB', connectionPool: 300 },
    baseCpuPct: 50,
    baseRamPct: 55,
    baseLatencyMs: 3,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'cache': {
    type: 'cache',
    category: 'storage',
    label: 'Cache',
    description: 'Ultra-fast in-memory key-value store (Redis / Memcached)',
    icon: '⚡',
    color: '#ef4444',
    defaultConfig: { replicas: 2, maxRps: 100000, ramGb: 32, cacheHitRate: 0.8, label: 'Cache Store', connectionPool: 1000 },
    baseCpuPct: 20,
    baseRamPct: 80,
    baseLatencyMs: 0.5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'object-store': {
    type: 'object-store',
    category: 'storage',
    label: 'Object Store',
    description: 'Scalable unstructured blob/file storage (AWS S3 / Google Cloud Storage)',
    icon: '🪣',
    color: '#84cc16',
    defaultConfig: { replicas: 1, maxRps: 5000, storageGb: 10000, label: 'Object Storage', connectionPool: 500 },
    baseCpuPct: 20,
    baseRamPct: 15,
    baseLatencyMs: 50,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'data-warehouse': {
    type: 'data-warehouse',
    category: 'storage',
    label: 'Data Warehouse',
    description: 'Analytical columnar storage for big data (Snowflake / BigQuery)',
    icon: '❄️',
    color: '#06b6d4',
    defaultConfig: { replicas: 1, maxRps: 2000, storageGb: 50000, label: 'Data Warehouse', connectionPool: 100 },
    baseCpuPct: 80,
    baseRamPct: 75,
    baseLatencyMs: 100,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'vector-db': {
    type: 'vector-db',
    category: 'storage',
    label: 'Vector DB',
    description: 'Optimized index for high-dimensional vector embeddings (Pinecone / Milvus)',
    icon: '📐',
    color: '#10b981',
    defaultConfig: { replicas: 2, maxRps: 4000, storageGb: 200, label: 'Vector DB', connectionPool: 200 },
    baseCpuPct: 60,
    baseRamPct: 50,
    baseLatencyMs: 15,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },

  // === MESSAGING ===
  'message-queue': {
    type: 'message-queue',
    category: 'messaging',
    label: 'Message Queue',
    description: 'Point-to-point asynchronous queue (RabbitMQ / ActiveMQ)',
    icon: '📬',
    color: '#ec4899',
    defaultConfig: { replicas: 2, maxRps: 50000, storageGb: 200, label: 'Message Queue', connectionPool: 1000 },
    baseCpuPct: 30,
    baseRamPct: 40,
    baseLatencyMs: 8,
    accumulatesStorage: true,
    isSource: false,
    isSink: false,
  },
  'pub-sub': {
    type: 'pub-sub',
    category: 'messaging',
    label: 'Pub/Sub',
    description: 'One-to-many asynchronous pub/sub router (Google Pub/Sub / AWS SNS)',
    icon: '📡',
    color: '#f43f5e',
    defaultConfig: { replicas: 2, maxRps: 100000, label: 'Pub/Sub Broker', connectionPool: 2000 },
    baseCpuPct: 20,
    baseRamPct: 25,
    baseLatencyMs: 5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'event-stream': {
    type: 'event-stream',
    category: 'messaging',
    label: 'Event Stream',
    description: 'High-throughput event streams with persistence (Kinesis)',
    icon: '🌊',
    color: '#f97316',
    defaultConfig: { replicas: 3, maxRps: 80000, storageGb: 1000, label: 'Event Stream', connectionPool: 1000 },
    baseCpuPct: 35,
    baseRamPct: 45,
    baseLatencyMs: 6,
    accumulatesStorage: true,
    isSource: false,
    isSink: false,
  },
  'kafka': {
    type: 'kafka',
    category: 'messaging',
    label: 'Kafka',
    description: 'Distributed event streaming platform with high retention and scaling',
    icon: '📦',
    color: '#ffffff',
    defaultConfig: { replicas: 3, maxRps: 120000, storageGb: 2000, label: 'Kafka Cluster', connectionPool: 2000 },
    baseCpuPct: 30,
    baseRamPct: 50,
    baseLatencyMs: 4,
    accumulatesStorage: true,
    isSource: false,
    isSink: false,
  },

  // === OBSERVABILITY ===
  'metrics': {
    type: 'metrics',
    category: 'observability',
    label: 'Metrics',
    description: 'Collects and aggregates system performance metrics (Prometheus)',
    icon: '📈',
    color: '#f97316',
    defaultConfig: { replicas: 1, maxRps: 50000, storageGb: 200, label: 'Metrics Store', connectionPool: 500 },
    baseCpuPct: 30,
    baseRamPct: 40,
    baseLatencyMs: 2,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'logs': {
    type: 'logs',
    category: 'observability',
    label: 'Logs',
    description: 'Aggregates application log streams (Elasticsearch / Loki)',
    icon: '📝',
    color: '#38bdf8',
    defaultConfig: { replicas: 2, maxRps: 40000, storageGb: 500, label: 'Log Collector', connectionPool: 500 },
    baseCpuPct: 40,
    baseRamPct: 50,
    baseLatencyMs: 5,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'tracing': {
    type: 'tracing',
    category: 'observability',
    label: 'Tracing',
    description: 'Distributed request tracing collector (Jaeger / Zipkin)',
    icon: '🕸️',
    color: '#60a5fa',
    defaultConfig: { replicas: 1, maxRps: 30000, storageGb: 300, label: 'Tracing Collector', connectionPool: 500 },
    baseCpuPct: 30,
    baseRamPct: 45,
    baseLatencyMs: 10,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'alerting': {
    type: 'alerting',
    category: 'observability',
    label: 'Alerting',
    description: 'Evaluates alerts and routes notifications (PagerDuty / Alertmanager)',
    icon: '⚠️',
    color: '#f43f5e',
    defaultConfig: { replicas: 1, maxRps: 10000, label: 'Alert Manager', timeoutMs: 1000 },
    baseCpuPct: 15,
    baseRamPct: 20,
    baseLatencyMs: 1,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'health-check': {
    type: 'health-check',
    category: 'observability',
    label: 'Health Check',
    description: 'Periodically monitors system availability and heartbeat status',
    icon: '💓',
    color: '#10b981',
    defaultConfig: { replicas: 1, maxRps: 5000, label: 'Health Prober', timeoutMs: 2000 },
    baseCpuPct: 10,
    baseRamPct: 15,
    baseLatencyMs: 2,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },

  // === NETWORK ===
  'vpc': {
    type: 'vpc',
    category: 'network',
    label: 'VPC',
    description: 'Virtual Private Cloud isolating virtual network resources',
    icon: '☁️',
    color: '#6366f1',
    defaultConfig: { label: 'Isolated VPC' },
    baseCpuPct: 5,
    baseRamPct: 10,
    baseLatencyMs: 0.1,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'subnet': {
    type: 'subnet',
    category: 'network',
    label: 'Subnet',
    description: 'Logical partition of a VPC network address space',
    icon: '🌐',
    color: '#4f46e5',
    defaultConfig: { label: 'Subnet Block' },
    baseCpuPct: 5,
    baseRamPct: 10,
    baseLatencyMs: 0.2,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
};

export const CATEGORIES: { id: ComponentCategory; label: string; icon: string }[] = [
  { id: 'client', label: 'CLIENT', icon: '👥' },
  { id: 'traffic-edge', label: 'TRAFFIC & EDGE', icon: '🔗' },
  { id: 'compute', label: 'COMPUTE', icon: '💻' },
  { id: 'storage', label: 'STORAGE', icon: '💾' },
  { id: 'messaging', label: 'MESSAGING', icon: '📨' },
  { id: 'observability', label: 'OBSERVABILITY', icon: '📡' },
  { id: 'network', label: 'NETWORK', icon: '🕸️' },
];
