import type { ComponentType, ComponentCategory, ComponentConfig } from '../../types';

export interface ComponentDefinition {
  type: ComponentType;
  category: ComponentCategory;
  label: string;
  description: string;
  icon: string;
  color: string;
  defaultConfig: ComponentConfig;
  // Baseline resource usage at 100% load
  baseCpuPct: number;
  baseRamPct: number;
  baseLatencyMs: number;
  // Can accumulate storage?
  accumulatesStorage: boolean;
  // Is a source node (generates requests)?
  isSource: boolean;
  // Is a sink node (consumes requests without forwarding)?
  isSink: boolean;
}

export const COMPONENT_DEFINITIONS: Record<ComponentType, ComponentDefinition> = {
  'web-client': {
    type: 'web-client',
    category: 'client',
    label: 'Web Client',
    description: 'Browser-based client generating HTTP requests',
    icon: '🌐',
    color: '#6366f1',
    defaultConfig: { replicas: 1, maxRps: 1000, cpuCores: 2, ramGb: 4, storageGb: 0, label: 'Web Client' },
    baseCpuPct: 10,
    baseRamPct: 20,
    baseLatencyMs: 0,
    accumulatesStorage: false,
    isSource: true,
    isSink: false,
  },
  'mobile-client': {
    type: 'mobile-client',
    category: 'client',
    label: 'Mobile Client',
    description: 'Mobile app generating API requests',
    icon: '📱',
    color: '#8b5cf6',
    defaultConfig: { replicas: 1, maxRps: 500, cpuCores: 1, ramGb: 2, storageGb: 0, label: 'Mobile Client' },
    baseCpuPct: 5,
    baseRamPct: 10,
    baseLatencyMs: 0,
    accumulatesStorage: false,
    isSource: true,
    isSink: false,
  },
  'load-balancer': {
    type: 'load-balancer',
    category: 'network',
    label: 'Load Balancer',
    description: 'Distributes traffic across multiple servers',
    icon: '⚖️',
    color: '#0ea5e9',
    defaultConfig: { replicas: 2, maxRps: 50000, cpuCores: 4, ramGb: 8, storageGb: 0, label: 'Load Balancer' },
    baseCpuPct: 15,
    baseRamPct: 20,
    baseLatencyMs: 1,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'cdn': {
    type: 'cdn',
    category: 'network',
    label: 'CDN',
    description: 'Content Delivery Network — caches static assets globally',
    icon: '🌍',
    color: '#06b6d4',
    defaultConfig: { replicas: 1, maxRps: 100000, cpuCores: 8, ramGb: 32, storageGb: 500, cacheHitRate: 0.85, label: 'CDN' },
    baseCpuPct: 10,
    baseRamPct: 30,
    baseLatencyMs: 5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'api-gateway': {
    type: 'api-gateway',
    category: 'network',
    label: 'API Gateway',
    description: 'Centralized entry point for API requests with routing & auth',
    icon: '🔀',
    color: '#14b8a6',
    defaultConfig: { replicas: 2, maxRps: 20000, cpuCores: 4, ramGb: 8, storageGb: 0, label: 'API Gateway' },
    baseCpuPct: 25,
    baseRamPct: 30,
    baseLatencyMs: 3,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'app-server': {
    type: 'app-server',
    category: 'compute',
    label: 'App Server',
    description: 'Application server handling business logic',
    icon: '🖥️',
    color: '#f59e0b',
    defaultConfig: { replicas: 3, maxRps: 2000, cpuCores: 4, ramGb: 16, storageGb: 20, label: 'App Server' },
    baseCpuPct: 60,
    baseRamPct: 50,
    baseLatencyMs: 20,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'microservice': {
    type: 'microservice',
    category: 'compute',
    label: 'Microservice',
    description: 'Lightweight single-responsibility service',
    icon: '⚙️',
    color: '#f97316',
    defaultConfig: { replicas: 2, maxRps: 3000, cpuCores: 2, ramGb: 8, storageGb: 10, label: 'Microservice' },
    baseCpuPct: 40,
    baseRamPct: 35,
    baseLatencyMs: 10,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'redis-cache': {
    type: 'redis-cache',
    category: 'cache',
    label: 'Redis Cache',
    description: 'In-memory key-value store with high throughput',
    icon: '⚡',
    color: '#ef4444',
    defaultConfig: { replicas: 2, maxRps: 100000, cpuCores: 4, ramGb: 32, storageGb: 0, cacheHitRate: 0.8, label: 'Redis Cache' },
    baseCpuPct: 20,
    baseRamPct: 80,
    baseLatencyMs: 0.5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'memcached': {
    type: 'memcached',
    category: 'cache',
    label: 'Memcached',
    description: 'Distributed memory caching system',
    icon: '🔥',
    color: '#dc2626',
    defaultConfig: { replicas: 2, maxRps: 80000, cpuCores: 4, ramGb: 16, storageGb: 0, cacheHitRate: 0.75, label: 'Memcached' },
    baseCpuPct: 15,
    baseRamPct: 85,
    baseLatencyMs: 1,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'sql-db': {
    type: 'sql-db',
    category: 'database',
    label: 'SQL Database',
    description: 'Relational database (PostgreSQL / MySQL)',
    icon: '🐘',
    color: '#3b82f6',
    defaultConfig: { replicas: 1, maxRps: 5000, cpuCores: 8, ramGb: 32, storageGb: 500, label: 'SQL Database' },
    baseCpuPct: 70,
    baseRamPct: 60,
    baseLatencyMs: 5,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'nosql-db': {
    type: 'nosql-db',
    category: 'database',
    label: 'NoSQL Database',
    description: 'Document / key-value store (MongoDB / DynamoDB)',
    icon: '🍃',
    color: '#22c55e',
    defaultConfig: { replicas: 3, maxRps: 15000, cpuCores: 8, ramGb: 32, storageGb: 1000, label: 'NoSQL Database' },
    baseCpuPct: 50,
    baseRamPct: 55,
    baseLatencyMs: 3,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'timeseries-db': {
    type: 'timeseries-db',
    category: 'database',
    label: 'Time-Series DB',
    description: 'Optimized for time-stamped data (InfluxDB / TimescaleDB)',
    icon: '📈',
    color: '#a855f7',
    defaultConfig: { replicas: 2, maxRps: 30000, cpuCores: 8, ramGb: 16, storageGb: 2000, label: 'Time-Series DB' },
    baseCpuPct: 45,
    baseRamPct: 50,
    baseLatencyMs: 2,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'message-queue': {
    type: 'message-queue',
    category: 'messaging',
    label: 'Message Queue',
    description: 'Async message broker (Kafka / RabbitMQ)',
    icon: '📬',
    color: '#ec4899',
    defaultConfig: { replicas: 3, maxRps: 50000, cpuCores: 8, ramGb: 16, storageGb: 200, label: 'Message Queue' },
    baseCpuPct: 30,
    baseRamPct: 40,
    baseLatencyMs: 8,
    accumulatesStorage: true,
    isSource: false,
    isSink: false,
  },
  'event-bus': {
    type: 'event-bus',
    category: 'messaging',
    label: 'Event Bus',
    description: 'Pub/sub event routing (SNS / EventBridge)',
    icon: '📡',
    color: '#f43f5e',
    defaultConfig: { replicas: 2, maxRps: 100000, cpuCores: 4, ramGb: 8, storageGb: 0, label: 'Event Bus' },
    baseCpuPct: 20,
    baseRamPct: 25,
    baseLatencyMs: 5,
    accumulatesStorage: false,
    isSource: false,
    isSink: false,
  },
  'object-storage': {
    type: 'object-storage',
    category: 'storage',
    label: 'Object Storage',
    description: 'Blob/file storage (S3 / GCS)',
    icon: '🪣',
    color: '#84cc16',
    defaultConfig: { replicas: 1, maxRps: 5000, cpuCores: 4, ramGb: 8, storageGb: 10000, label: 'Object Storage' },
    baseCpuPct: 20,
    baseRamPct: 15,
    baseLatencyMs: 50,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
  'metrics-collector': {
    type: 'metrics-collector',
    category: 'monitoring',
    label: 'Metrics Collector',
    description: 'Aggregates metrics (Prometheus / Datadog)',
    icon: '📊',
    color: '#64748b',
    defaultConfig: { replicas: 1, maxRps: 50000, cpuCores: 4, ramGb: 16, storageGb: 100, label: 'Metrics Collector' },
    baseCpuPct: 30,
    baseRamPct: 40,
    baseLatencyMs: 2,
    accumulatesStorage: true,
    isSource: false,
    isSink: true,
  },
};

export const CATEGORIES: { id: ComponentCategory; label: string; icon: string }[] = [
  { id: 'client', label: 'Clients', icon: '👥' },
  { id: 'network', label: 'Network', icon: '🔗' },
  { id: 'compute', label: 'Compute', icon: '💻' },
  { id: 'cache', label: 'Cache', icon: '⚡' },
  { id: 'database', label: 'Database', icon: '🗄️' },
  { id: 'messaging', label: 'Messaging', icon: '📨' },
  { id: 'storage', label: 'Storage', icon: '💾' },
  { id: 'monitoring', label: 'Monitoring', icon: '📡' },
];
